# Generated by Django 4.0.5 on 2022-07-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0004_buku_cover_buku_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='buku',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
