# Generated by Django 4.0.5 on 2022-07-13 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0005_buku_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buku',
            name='date',
        ),
    ]
